In [1]:
import numpy as np

In [2]:
# Check the training-time forward pass by checking means and variances
# of features both before and after spatial batch normalization

N, C, H, W = 2, 3, 4, 5
x = 4 * np.random.randn(N, C, H, W) + 10

print 'Before spatial batch normalization:'
print '  Shape: ', x.shape
print '  Means: ', x.mean(axis=(0, 2, 3))
print '  Stds: ', x.std(axis=(0, 2, 3))

Before spatial batch normalization:
  Shape:  (2L, 3L, 4L, 5L)
  Means:  [  9.59715442  10.03317367   9.89386844]
  Stds:  [ 4.5333975   4.2305004   3.38258744]


In [2]:
test = np.random.randint(0,4,(5,6,4))
test.reshape(-1)

array([2, 3, 2, 0, 3, 2, 1, 1, 1, 1, 2, 0, 1, 2, 0, 2, 2, 3, 3, 3, 0, 3, 0,
       2, 3, 3, 2, 0, 1, 2, 3, 3, 0, 3, 2, 2, 2, 3, 1, 1, 3, 1, 3, 3, 3, 0,
       3, 3, 1, 2, 2, 2, 3, 1, 1, 3, 3, 0, 2, 3, 3, 2, 1, 2, 0, 1, 0, 2, 0,
       0, 3, 2, 0, 3, 0, 1, 3, 1, 1, 2, 0, 3, 1, 3, 2, 0, 3, 0, 3, 2, 3, 0,
       0, 1, 2, 3, 1, 1, 2, 0, 1, 1, 0, 2, 1, 3, 2, 0, 3, 0, 2, 2, 0, 3, 2,
       1, 0, 0, 3, 2])

In [3]:
a = np.random.random((3,3))
print a
print np.max(a)
print np.unravel_index(np.argmax(a),a.shape)

[[ 0.94982896  0.62966054  0.44539835]
 [ 0.23311198  0.8779362   0.90644193]
 [ 0.53099721  0.42083817  0.70804781]]
0.949828963817
(0, 0)


In [4]:
np.random.random(6)

array([ 0.44932497,  0.52428533,  0.04561412,  0.81186139,  0.01710238,
        0.17729956])

In [15]:
for i in range(test.shape[0]):
    test[i] = np.pad(test[i],(2,),mode='constant') 

ValueError: could not broadcast input array from shape (10,8) into shape (6,4)

In [19]:
test

array([[[0, 3, 0, 3],
        [0, 2, 2, 1],
        [2, 3, 2, 3],
        [3, 3, 0, 0],
        [2, 3, 1, 0],
        [2, 1, 1, 3]],

       [[3, 1, 2, 1],
        [2, 3, 2, 3],
        [1, 2, 0, 1],
        [2, 0, 0, 3],
        [3, 0, 0, 0],
        [3, 3, 1, 1]],

       [[0, 3, 3, 1],
        [2, 3, 1, 3],
        [0, 0, 1, 1],
        [3, 2, 2, 1],
        [2, 3, 1, 0],
        [1, 2, 3, 3]],

       [[3, 3, 0, 1],
        [1, 2, 2, 0],
        [0, 2, 2, 3],
        [2, 3, 2, 1],
        [0, 3, 1, 3],
        [2, 0, 0, 1]],

       [[3, 0, 1, 1],
        [0, 0, 2, 1],
        [0, 0, 3, 3],
        [3, 2, 1, 1],
        [3, 3, 0, 2],
        [1, 0, 2, 3]]])

In [24]:
a = range(0,10,2)
print a


[0, 2, 4, 6, 8]


In [25]:
a[1:3]

[2, 4]