In [8]:
import numpy as np
a = np.random.random((4,3))
print a
print np.argmax(a,axis=1)

[[ 0.10945075  0.16882076  0.98624407]
 [ 0.56810887  0.66007203  0.1053917 ]
 [ 0.78714684  0.29835866  0.64546859]
 [ 0.55039781  0.58042915  0.77400526]]
[2 1 0 2]


In [11]:
assert False, 'hello'

AssertionError: hello